// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAklRTNE5KieAt2xuQvN6ayKeEZ4yT-F0k',
//     appId: '1:312212886005:web:73c0ff1ee48dcc840790bc',
//     messagingSenderId: '312212886005',
//     projectId: 'foduu-comm',
//     authDomain: 'foduu-comm.firebaseapp.com',
//     storageBucket: 'foduu-comm.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDsbnzwrW5zq8qZ3-eu0U_CIQ6NXkJCzNQ',
//     appId: '1:312212886005:android:7092aa54f875a15b0790bc',
//     messagingSenderId: '312212886005',
//     projectId: 'foduu-comm',
//     storageBucket: 'foduu-comm.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBuMspfupRM7yyA2QB5JA8UlqCi0BPrZnc',
//     appId: '1:312212886005:ios:f0c2c2558121dd860790bc',
//     messagingSenderId: '312212886005',
//     projectId: 'foduu-comm',
//     storageBucket: 'foduu-comm.appspot.com',
//     iosBundleId: 'com.foduu.foduuEcommerce',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBuMspfupRM7yyA2QB5JA8UlqCi0BPrZnc',
//     appId: '1:312212886005:ios:f0c2c2558121dd860790bc',
//     messagingSenderId: '312212886005',
//     projectId: 'foduu-comm',
//     storageBucket: 'foduu-comm.appspot.com',
//     iosBundleId: 'com.foduu.foduuEcommerce',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAklRTNE5KieAt2xuQvN6ayKeEZ4yT-F0k',
//     appId: '1:312212886005:web:4d16d2d63bca82730790bc',
//     messagingSenderId: '312212886005',
//     projectId: 'foduu-comm',
//     authDomain: 'foduu-comm.firebaseapp.com',
//     storageBucket: 'foduu-comm.appspot.com',
//   );

// }
