// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSPFyXvfLUf27Eg4BXkCn8tZbK8PIz4S8',
    appId: '1:490586987672:web:73c0ff1ee48dcc840790bc', // Placeholder web ID
    messagingSenderId: '490586987672',
    projectId: 'fastify-flutter',
    authDomain: 'fastify-flutter.firebaseapp.com',
    storageBucket: 'fastify-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSPFyXvfLUf27Eg4BXkCn8tZbK8PIz4S8',
    appId: '1:490586987672:android:5e6a15ce63735e50c544ed',
    messagingSenderId: '490586987672',
    projectId: 'fastify-flutter',
    storageBucket: 'fastify-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSPFyXvfLUf27Eg4BXkCn8tZbK8PIz4S8',
    appId: '1:490586987672:ios:f0c2c2558121dd860790bc', // Placeholder iOS ID
    messagingSenderId: '490586987672',
    projectId: 'fastify-flutter',
    storageBucket: 'fastify-flutter.firebasestorage.app',
    iosBundleId: 'com.foduu.foduu_ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSPFyXvfLUf27Eg4BXkCn8tZbK8PIz4S8',
    appId: '1:490586987672:ios:f0c2c2558121dd860790bc', // Placeholder macOS ID
    messagingSenderId: '490586987672',
    projectId: 'fastify-flutter',
    storageBucket: 'fastify-flutter.firebasestorage.app',
    iosBundleId: 'com.foduu.foduu_ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSPFyXvfLUf27Eg4BXkCn8tZbK8PIz4S8',
    appId: '1:490586987672:web:4d16d2d63bca82730790bc', // Placeholder Windows ID
    messagingSenderId: '490586987672',
    projectId: 'fastify-flutter',
    authDomain: 'fastify-flutter.firebaseapp.com',
    storageBucket: 'fastify-flutter.firebasestorage.app',
  );
}
